server:
  port: 8080

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://user:password@localhost:8761/eureka
      
security:
  sessions: always
  
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: mediasocial-chat
          group: comments-chat
          content-type: application/json
        clientToBroker:
          destination: mediasocial-chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: mediasocial-chat-user-messages
          group: topic-chatMessages
          
    gateway: 
      routes: 
      # ======================================================== 
      - id: imagesService 
        uri: lb://IMAGES 
        predicates: 
        - Path=/imagesService/** 
        filters: 
        - RewritePath=/imagesService/(?<segment>.*), /$\{segment} 
        - RewritePath=/imagesService, / 
        - SaveSession 
      - id: images 
        uri: lb://IMAGES 
        predicates: 
        - Path=/images/** 
        filters: 
        - SaveSession 
      - id: mainCss 
        uri: lb://IMAGES 
        predicates: 
        - Path=/css/main.css 
        filters: 
        - SaveSession 
      - id: bootstrapCss 
        uri: lb://IMAGES 
        predicates: 
        - Path=/css/bootstrap.min.css
        filters: 
        - SaveSession 
      - id: jqueryJs 
        uri: lb://IMAGES 
        predicates: 
        - Path=/js/jquery.js
        filters: 
        - SaveSession 
      - id: popperJs 
        uri: lb://IMAGES 
        predicates: 
        - Path=/js/popper.min.js
        filters: 
        - SaveSession 
      - id: bootstrapJs 
        uri: lb://IMAGES 
        predicates: 
        - Path=/js/bootstrap.min.js
        filters: 
        - SaveSession 
      - id: commentsService 
        uri: lb://IMAGES 
        predicates: 
        - Path=/comments/** 
        filters: 
        - SaveSession 
