server:
  port: 8080
  
# tag::zuul[]
zuul:
  routes:
    imagesService:
      path: /imagesService/**
      serviceId: IMAGES
      sensitive-headers:
    images:
      path: /images/**
      serviceId: IMAGES
      sensitive-headers:
      stripPrefix: false
    mainCss:
      path: /main.css
      serviceId: IMAGES
      sensitive-headers:
    commentsService:
      path: /comments/**
      serviceId: IMAGES
      sensitive-headers:
      stripPrefix: false
# end::zuul[]

# tag::secured[]
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
# end::secured[]

# tag::security[]
security:
  sessions: always
# end::security[]

# tag::ribbon[]
zuul:
  ribbon-isolation-strategy: thread
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
# end::ribbon[]

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
