server:
  port: 8200

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
