server:
  port: 9000

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: mediasocial-comments
          group: comments-service
          content-type: application/json
        output:
          destination: mediasocial-chat
          group: comments-chat
          content-type: application/json
logging:
  level:
    com:
      cherubini: DEBUG
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG
        data: TRACE
    reactor:
      core: TRACE
      util: TRACE

management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: '*'
  endpoint:
    info:
      git:
        mode: full
    health:
      show-details: always   
