server:
  port: 8200
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: mediasocial-comments
          group: comments-service
          content-type: application/json
logging:
  level:
    com:
      cherubini: DEBUG
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG
        data: TRACE
    reactor:
      core: TRACE
      util: TRACE

management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: '*'
  endpoint:
    info:
      git:
        mode: full
    health:
      show-details: always   

  
