eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: mediasocial
        output:
          destination: mediasocial
          group: comments
          content-type: application/json

  
