eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: mediasocial-comments
          group: comments-service
          content-type: application/json

  
